version: '3'

services:

  jaguerMongo:
    image: jaguer/mongo
    build: mongo/.
    volumes:
      - ./mongo/data:/data/db
    networks:
      - jaguerNetwork
    ports:
      - "27027:27017"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  jaguerNode:
    image: jaguer/node
    build: app/.
    command: yarn dev
    depends_on:
      - 'jaguerMongo'
    volumes:
      - ./app/src:/usr/src/jaguer/src
      - ./app/bin:/usr/src/jaguer/bin
      - ./app/public:/usr/src/jaguer/public
    networks:
      - jaguerNetwork
    ports:
      - "2525:8080"
      - "2626:9229"
    env_file:
      enviroments.env

networks:
  jaguerNetwork:
