version: '3'

services:

  nodeLearn:
    image: carlos/nodelearn
    build: app/.
    container_name: nodeLearn
    command: yarn debug
    depends_on:
      - 'mongoLearn'
    volumes:
      - ./app/src:/usr/src/jaguer/src
      - ./app/bin:/usr/src/jaguer/bin
      - ./app/public:/usr/src/jaguer/public
    networks:
      - networkLearn
    ports:
      - "2525:8080"
      - "2626:9229"
    env_file:
      enviroments.env
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  mongoLearn:
    image: mongo:latest
    container_name: mongoLearn
    volumes:
      - ./mongo/data:/data/db
    networks:
      - networkLearn
    ports:
      - "27027:27017"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    

networks:
  networkLearn:
